/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/'use strict';

var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }

var _wp = wp,
    blocks = _wp.blocks,
    data = _wp.data,
    element = _wp.element,
    components = _wp.components,
    blockEditor = _wp.blockEditor;
var registerBlockType = blocks.registerBlockType;
var dispatch = data.dispatch,
    select = data.select;
var Fragment = element.Fragment;
var PanelBody = components.PanelBody,
    BaseControl = components.BaseControl,
    Icon = components.Icon,
    RangeControl = components.RangeControl,
    IconButton = components.IconButton,
    Toolbar = components.Toolbar,
    SelectControl = components.SelectControl;
var InnerBlocks = blockEditor.InnerBlocks,
    RichText = blockEditor.RichText,
    InspectorControls = blockEditor.InspectorControls,
    PanelColorSettings = blockEditor.PanelColorSettings,
    MediaUpload = blockEditor.MediaUpload,
    BlockControls = blockEditor.BlockControls;

var __ = Drupal.t;

var undrrHeroSettings = {
  title: __('UNDRR Hero block'),
  description: __('A hero to call attention'),
  icon: 'admin-site-alt3',
  attributes: {
    title: {
      type: 'string'
    },
    subtitle: {
      type: 'string'
    },
    text: {
      type: 'string'
    }
  },

  edit: function edit(_ref) {
    var className = _ref.className,
        attributes = _ref.attributes,
        setAttributes = _ref.setAttributes,
        isSelected = _ref.isSelected;
    var title = attributes.title,
        subtitle = attributes.subtitle,
        text = attributes.text;


    return React.createElement(
      Fragment,
      null,
      React.createElement(
        'section',
        { className: className + ' vf-hero | vf-u-fullbleed' },
        React.createElement(
          'div',
          { className: 'vf-hero__content | vf-box | vf-stack vf-stack--400' },
          React.createElement(RichText, {
            identifier: 'title',
            tagName: 'h2',
            value: title,
            placeholder: __('Title'),
            onChange: function onChange(nextTitle) {
              setAttributes({
                title: nextTitle
              });
            },
            onSplit: function onSplit() {
              return null;
            },
            unstableOnSplit: function unstableOnSplit() {
              return null;
            }
          }),
          React.createElement(RichText, {
            identifier: 'subtitle',
            tagName: 'div',
            value: subtitle,
            placeholder: __('Subtitle goes here'),
            onChange: function onChange(nextSubtitle) {
              setAttributes({
                subtitle: nextSubtitle
              });
            },
            onSplit: function onSplit() {
              return null;
            },
            unstableOnSplit: function unstableOnSplit() {
              return null;
            }
          }),
          React.createElement(RichText, {
            identifier: 'text',
            tagName: 'p',
            value: text,
            placeholder: __('Text'),
            onChange: function onChange(nextText) {
              setAttributes({
                text: nextText
              });
            }
          })
        )
      ),
      React.createElement(
        InspectorControls,
        null,
        React.createElement(
          PanelBody,
          { title: __('Block Settings') },
          React.createElement(
            'div',
            null,
            title
          )
        )
      )
    );
  },
  save: function save(_ref2) {
    var className = _ref2.className,
        attributes = _ref2.attributes;
    var title = attributes.title,
        subtitle = attributes.subtitle,
        text = attributes.text;


    return React.createElement(
      'section',
      { className: className + ' vf-hero | vf-u-fullbleed' },
      React.createElement(
        'div',
        { className: 'vf-hero__content | vf-box | vf-stack vf-stack--400' },
        title && React.createElement(
          'h2',
          { 'class': 'vf-hero__heading' },
          title
        ),
        subtitle && React.createElement(
          'p',
          { 'class': 'vf-hero__subheading' },
          subtitle
        ),
        text && React.createElement(
          'p',
          { 'class': 'vf-hero__text' },
          text
        ),
        React.createElement(
          'a',
          { 'class': 'vf-hero__link', href: 'JavaScript:Void(0);' },
          'Learn more',
          React.createElement(
            'svg',
            { width: '24', height: '24', xmlns: 'http://www.w3.org/2000/svg' },
            React.createElement('path', { d: 'M0 12c0 6.627 5.373 12 12 12s12-5.373 12-12S18.627 0 12 0C5.376.008.008 5.376 0 12zm13.707-5.209l4.5 4.5a1 1 0 010 1.414l-4.5 4.5a1 1 0 01-1.414-1.414l2.366-2.367a.25.25 0 00-.177-.424H6a1 1 0 010-2h8.482a.25.25 0 00.177-.427l-2.366-2.368a1 1 0 011.414-1.414z', fill: '', 'fill-rule': 'nonzero' })
          )
        )
      )
    );
  }
};

var exampleBlockSettings = {
  title: __('UNDRR Example Block'),
  description: __('UNDRR Example Block'),
  icon: 'welcome-learn-more',
  attributes: {
    title: {
      type: 'string'
    },
    subtitle: {
      type: 'string'
    },
    text: {
      type: 'string'
    }
  },

  edit: function edit(_ref3) {
    var className = _ref3.className,
        attributes = _ref3.attributes,
        setAttributes = _ref3.setAttributes,
        isSelected = _ref3.isSelected;
    var title = attributes.title,
        subtitle = attributes.subtitle,
        text = attributes.text;


    return React.createElement(
      Fragment,
      null,
      React.createElement(
        'div',
        { className: className },
        React.createElement(
          'div',
          { className: 'column' },
          React.createElement(RichText, {
            identifier: 'title',
            tagName: 'h2',
            value: title,
            placeholder: __('Title'),
            onChange: function onChange(nextTitle) {
              setAttributes({
                title: nextTitle
              });
            },
            onSplit: function onSplit() {
              return null;
            },
            unstableOnSplit: function unstableOnSplit() {
              return null;
            }
          }),
          React.createElement(RichText, {
            identifier: 'subtitle',
            tagName: 'div',
            value: subtitle,
            placeholder: __('Subtitle goes here'),
            onChange: function onChange(nextSubtitle) {
              setAttributes({
                subtitle: nextSubtitle
              });
            },
            onSplit: function onSplit() {
              return null;
            },
            unstableOnSplit: function unstableOnSplit() {
              return null;
            }
          }),
          React.createElement(RichText, {
            identifier: 'text',
            tagName: 'p',
            value: text,
            placeholder: __('Text'),
            onChange: function onChange(nextText) {
              setAttributes({
                text: nextText
              });
            }
          })
        ),
        React.createElement(
          'div',
          { className: 'column' },
          React.createElement(
            'div',
            { className: 'icon' },
            React.createElement(Icon, { icon: 'welcome-learn-more' })
          ),
          isSelected && React.createElement(
            'div',
            { className: 'info' },
            React.createElement(
              'p',
              null,
              'This is Gutenberg\'s example block.'
            ),
            React.createElement(
              'p',
              null,
              'To test it just fill the "fields" on the left and save.'
            )
          )
        )
      ),
      React.createElement(
        InspectorControls,
        null,
        React.createElement(
          PanelBody,
          { title: __('Block Settings') },
          React.createElement(
            'div',
            null,
            title
          )
        )
      )
    );
  },
  save: function save(_ref4) {
    var className = _ref4.className,
        attributes = _ref4.attributes;
    var title = attributes.title,
        subtitle = attributes.subtitle,
        text = attributes.text;


    return React.createElement(
      'div',
      { className: className },
      React.createElement(
        'div',
        { className: 'column' },
        title && React.createElement(
          'h2',
          null,
          title
        ),
        subtitle && React.createElement(
          'div',
          null,
          subtitle
        ),
        text && React.createElement(
          'p',
          null,
          text
        )
      ),
      React.createElement(
        'div',
        { className: 'column' },
        React.createElement(
          'div',
          { className: 'icon' },
          React.createElement(Icon, { icon: 'welcome-learn-more' })
        )
      )
    );
  }
};

var dynamicBlockSettings = {
  title: __('UNDRR Example Dynamic Block'),
  description: __('UNDRR example dynamic block that can be rendered server-side.'),
  icon: 'welcome-learn-more',
  attributes: {
    title: {
      type: 'string'
    }
  },

  edit: function edit(_ref5) {
    var className = _ref5.className,
        attributes = _ref5.attributes,
        setAttributes = _ref5.setAttributes,
        isSelected = _ref5.isSelected;
    var title = attributes.title;


    return React.createElement(
      'div',
      { className: className },
      React.createElement(
        'div',
        null,
        '\u2014 Hello from the Gutenberg JS editor.'
      ),
      React.createElement(
        'div',
        { className: 'dynamic-block-title' },
        React.createElement(RichText, {
          identifier: 'title',
          tagName: 'h2',
          value: title,
          placeholder: __('Title goes here'),
          onChange: function onChange(title) {
            setAttributes({
              title: title
            });
          },
          onSplit: function onSplit() {
            return null;
          },
          unstableOnSplit: function unstableOnSplit() {
            return null;
          }
        })
      ),
      React.createElement(
        'div',
        { className: 'dynamic-block-content' },
        React.createElement(InnerBlocks, null)
      )
    );
  },
  save: function save(_ref6) {
    var className = _ref6.className,
        attributes = _ref6.attributes;
    var title = attributes.title;

    return React.createElement(
      'div',
      { className: className },
      title && React.createElement(
        'h2',
        null,
        title
      ),
      React.createElement(InnerBlocks.Content, null)
    );
  }
};

var category = {
  slug: 'undrr',
  title: __('UNDRR')
};

var currentCategories = select('core/blocks').getCategories().filter(function (item) {
  return item.slug !== category.slug;
});
dispatch('core/blocks').setCategories([category].concat(_toConsumableArray(currentCategories)));

registerBlockType(category.slug + '/undrr-hero-block', _extends({ category: category.slug }, undrrHeroSettings));
registerBlockType(category.slug + '/example-block', _extends({ category: category.slug }, exampleBlockSettings));
registerBlockType(category.slug + '/dynamic-block', _extends({ category: category.slug }, dynamicBlockSettings));